//
//  ModelData.swift
//  YaTon Project
//
//  Created by 변재은 on 2022/09/14.
//

import Foundation

struct ModelData {
    var mountainEquipments = [
        MountainEquipment(name: "노스페이스 시티 칠러 자켓 NJ3LN01C",
                          price: 105320,
                          category: .northFace,
                          imageName: "NJ3LN01C"),
        MountainEquipment(name: "노스페이스 프리 라이트 자켓 NJ3BN04B",
                          price: 105320,
                          category: .northFace,
                          imageName: "NJ3BN04B"),
        MountainEquipment(name: "노스페이스 하이 마운틴 에코 아노락 NJ3BN04L",
                          price: 126520,
                          category: .northFace,
                          imageName: "NJ3BN04L"),
        MountainEquipment(name: "노스페이스 화이트라벨 올레마 자켓 NA3BN12A",
                          price: 97540,
                          category: .northFace,
                          imageName: "NA3BN12A"),
        MountainEquipment(name: "디스커버리 익스페디션 경량 블루종넥 바람막이 DMWJ73023",
                          price: 169000,
                          category: .discovery,
                          imageName: "DMWJ73023"),
        MountainEquipment(name: "디스커버리 익스페디션 경량 패커블 바람막이 DMWJ75023",
                          price: 149000,
                          category: .discovery,
                          imageName: "DMWJ75023"),
        MountainEquipment(name: "디스커버리 익스페디션 경량 아노락 바람막이 DXWJ55023",
                          price: 111290,
                          category: .discovery,
                          imageName: "DXWJ55023"),
        MountainEquipment(name: "디스커버리 익스페디션 경량 윈드레이저 바람막이 DMWJ61023",
                          price: 169000,
                          category: .discovery,
                          imageName: "DMWJ61023"),
        MountainEquipment(name: "아이더 루치아노 경량 리플렉티브 방풍 자켓 DMM22103",
                          price: 149000,
                          category: .eider,
                          imageName: "DMM22103"),
        MountainEquipment(name: "아이더 루크 경량 스트레치 아노락 DUM22101",
                          price: 139000,
                          category: .eider,
                          imageName: "DUM22101"),
        MountainEquipment(name: "아이더 플레르 경량 하이브리드 방풍 자켓 DMM22111",
                          price: 133850,
                          category: .eider,
                          imageName: "DMM22111"),
        MountainEquipment(name: "아이더 쉴드 홑겹 자켓 DMM22161",
                          price: 169000,
                          category: .eider,
                          imageName: "DMM22161"),
        MountainEquipment(name: "네파 C-TR 사이론 경량 자켓 7I30664",
                          price: 119000,
                          category: .nepa,
                          imageName: "7I30664"),
        MountainEquipment(name: "네파 액티브 컬러블럭 윈드 자켓 7I30621",
                          price: 121080,
                          category: .nepa,
                          imageName: "7I30621"),
        MountainEquipment(name: "네파 프레스토 인피니움 자켓 7I10621",
                          price: 101430,
                          category: .nepa,
                          imageName: "7I10621"),
        MountainEquipment(name: "네파 베이퍼 스트레치 자켓 7I30623",
                          price: 111300,
                          category: .nepa,
                          imageName: "7I30623"),
        MountainEquipment(name: "컬럼비아 팬로즈 생츄어리 II 자켓 C32-YM3221",
                          price: 111300,
                          category: .columbia,
                          imageName: "C32-YM3221"),
        MountainEquipment(name: "컬럼비아 블랙스톤 릿지 자켓 C32-YM3223",
                          price: 169000,
                          category: .columbia,
                          imageName: "C32-YM3223"),
        MountainEquipment(name: "컬럼비아 와타로아 돔 II 자켓 C31-YM3201",
                          price: 125300,
                          category: .columbia,
                          imageName: "C31-YM3201"),
        MountainEquipment(name: "컬럼비아 조지 포레스트 자켓 C31-YM3204",
                          price: 181300,
                          category: .columbia,
                          imageName: "C31-YM3204")
    ]
}
